version: '3'
services:
    fastdfs_tracker:
      image: season/fastdfs:1.2
      container_name: fastdfs_tracker      
      restart: always
      entrypoint: "/entrypoint.sh tracker"
      volumes:
        - ./tracker/data:/fastdfs/tracker/data
        - ./tracker/fdfs:/etc/fdfs
      ports:
        - 22122:22122

    fastdfs_storage:
      container_name: fastdfs_storage
      image: season/fastdfs:1.2
      restart: always
      entrypoint: "/entrypoint.sh storage"
      environment:
        TRACKER_SERVER: fastdfs_tracker:22122
      volumes:
        - ./data/storage:/fasdfs/storage_path
      depends_on:
        - fastdfs_tracker
      links:
        - fastdfs_tracker
    
