version: '3'
services:
    fastdfs_tracker:
      image: season/fastdfs:1.2
      container_name: fastdfs_tracker      
      restart: always
      entrypoint: "/entrypoint.sh tracker"
      volumes:
        - ./tracker/data:/fastdfs/tracker/data
      ports:
        - 22122:22122
        

    fastdfs_storage:
      container_name: fastdfs_storage
      image: season/fastdfs:1.2
      restart: always
      entrypoint: "/entrypoint.sh storage"
      environment:
        TRACKER_SERVER: fastdfs_tracker:22122
      volumes:
        - ./data/storage:/fastdfs/store_path
      depends_on:
        - fastdfs_tracker
      links:
        - fastdfs_tracker
    
    fastdfs_nginx:
      container_name: fastdfs_nginx
      image: season/fastdfs:1.2
      restart: always
      entrypoint: "/entrypoint.sh nginx"
      environment:
        TRACKER_SERVER: fastdfs_tracker:22122
      volumes:
        - ./data/storage:/fastdfs/store_path
        - ./nginx_conf/nginx.conf:/etc/nginx/conf/nginx.conf
      ports:
        - 8888:80
      depends_on:
        - fastdfs_storage
      links:
        - fastdfs_storage
