mindoc:
  image: registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc:v2.0-beta.2 
  container_name: mindoc-app
  privileged: true
  restart: always
  net: host
  # ports:
  #  - 8082:8181
  volumes:
    - ./database:/mindoc/database
    - ./uploads:/mindoc/uploads
    - /etc/localtime:/etc/localtime
  mem_limit: 800m
  environment:
    - MINDOC_RUN_MODE=prod
    - MINDOC_DB_ADAPTER=sqlite3
    - MINDOC_DB_DATABASE=./database/mindoc.db
    - MINDOC_CACHE=true
    - MINDOC_CACHE_PROVIDER=file
    - MINDOC_ENABLE_EXPORT=false
    - MINDOC_BASE_URL= 
    - MINDOC_CDN_IMG_URL=
    - MINDOC_CDN_CSS_URL=
    - MINDOC_CDN_JS_URL= 
    - TZ=Asia/Shanghai
  dns:
    - 223.5.5.5
    - 223.6.6.6